logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    org.springframework.boot.autoconfigure.web: debug
    reactor.netty: debug

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true

spring:
  application:
    name: travel-agency-gateway

  zipkin:
    base-url: http://localhost:9411/

  cloud:

    # Debug routes
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true

      routes:

      - id: travel-agent-service
        uri: lb://travel-agent-service
        predicates:
        - Path=/api/v1/booking/trip,/api/v2/booking/trip

      - id: hotel-reservation-service
        uri: lb://hotel-reservation-service
        predicates:
        - Path=/api/v1/hotes,/api/v1/hotes/{hotelId},/api/v1/hotes/{reservationId}/cancelled

      - id: flight-reservation-service
        uri: lb://flight-reservation-service
        predicates:
        - Path=/api/v1/flights,/api/v1/flights/{flightId},/api/v1/flights/{reservationId}/cancelled

      - id: car-rental-service
        uri: lb://car-rental-service
        predicates:
          - Path=/api/v1/cars,/api/v1/cars/{carId},/api/v1/cars/{reservationId}/cancelled