spring.application.name: eureka-server

server:
  port: 8761

spring:
  security.user:
    name: eurekaUser
    password: eurekaPassword

eureka:
#  instance:
#    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging.level:
  com.netflix.eureka: OFF
  com.netflix.discovery: OFF