# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - 3306:3306

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 9091:8080

  activemq:
    image: vromero/activemq-artemis
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: simetraehcapa
    ports:
      - 8161:8161
      - 61616:61616
      
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - 9411:9411

  mongo:
    image: mongo:3.6.23
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoUser

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoUser