server.port: 8082

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  cloud:
    config:
      override-system-properties: false

  # defaults for this docker image - vromero/activemq-artemis
  artemis:
    user: artemis
    password: simetraehcapa