package tech.travel.agent.sm;

public enum ReservationState {
    NEW,
    INITIALIZED,
    FLIGHT_IN_PROGRESS,
    FLIGHT_COMPLETED,
    FLIGHT_CANCELLATION_IN_PROGRESS,
    FLIGHT_CANCELLED,
    HOTEL_IN_PROGRESS,
    HOTEL_COMPLETED,
    HOTEL_CANCELLATION_IN_PROGRESS,
    HOTEL_CANCELED,
    CAR_IN_PROGRESS,
    CAR_COMPLETED,
    CAR_CANCELLATION_IN_PROGRESS,
    CAR_CANCELLED,
    MANUAL_INTERVENTION_REQUIRED,
    NOT_AVAILABLE,
    COMPLETED
}
